[package]
name = "deadbeef-plugin-discord-rpc"
version = "0.1.0"
edition = "2024"

[dependencies]
discord-rich-presence = "1.0.0"
lazy_static = "1.5.0"
once_cell = "1.21.3"

[build-dependencies]
bindgen = "0.71.0"

[lib]
crate-type = ["cdylib"]
